//planing
export const LOAD_PLANING_LIST = 'LOAD_PLANING_LIST';
export const LOAD_PLANING_SUCCESS = 'LOAD_PLANING_SUCCESS';
export const LOAD_PLANING_ERROR = 'LOAD_PLANING_ERROR';

export const LOAD_PLANING_COLUMN = 'LOAD_PLANING_COLUMN';
export const LOAD_PLANING_COLUMN_SUCCESS = 'LOAD_PLANING_COLUMN_SUCCESS';
export const LOAD_PLANING_COLUMN_ERROR = 'LOAD_PLANING_COLUMN_ERROR';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
// export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';

/// comments

export const LOAD_COMMENTS_LIST = 'LOAD_COMMENTS_LIST';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_ERROR = 'LOAD_COMMENTS_ERROR';

export const CREATE_COMMENTS_START = 'CREATE_COMMENTS_START';
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_ERROR = 'CREATE_COMMENTS_ERROR';

export const CREATE_COMMENTS_RELPY_START = 'CREATE_COMMENTS_RELPY_START';
export const CREATE_COMMENTS_RELPY_SUCCESS = 'CREATE_COMMENTS_RELPY_SUCCESS';
export const CREATE_COMMENTS_RELPY_ERROR = 'CREATE_COMMENTS_RELPY_ERROR';


export const DELETE_COMMENTS_START = 'DELETE_COMMENTS_START';
export const DELETE_COMMENTS_SUCCESS = 'DELETE_COMMENTS_SUCCESS';
export const DELETE_COMMENTS_ERROR = 'DELETE_COMMENTS_ERROR';








// export const SET_PLANING_QUEUE_LIST = 'SET_PLANING_QUEUE_LIST';
// export const GET_PLANING_QUEUE_LIST = 'GET_PLANING_QUEUE_LIST';

// export const SET_PLANING_DEV_LIST = 'SET_PLANING_DEV_LIST';
// export const GET_PLANING_DEV_LIST = 'GET_PLANING_DEV_LIST';

// export const SET_PLANING_DONE_LIST = 'SET_PLANING_DONE_LIST';
// export const GET_PLANING_DONE_LIST = 'GET_PLANING_DONE_LIST';


// export const GET_PLANING_LIST = 'GET_PLANING_LIST';
// export const SET_PLANING_LIST = 'SET_PLANING_LIST';

// export const GET_CONSTRUCTION_LIST = 'GET_CONSTRUCTION_LIST';
// export const SET_CONSTRUCTION_LIST = 'SET_CONSTRUCTION_LIST';

// export const GET_DEV_LIST = 'GET_DEV_LIST';
// export const SET_DEV_LIST = 'SET_DEV_LIST';

// export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
// export const UPDATE_REQUEST = 'UPDATE_REQUEST';

